name: Telegram Downloader

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade pip
          pip install yt-dlp

      - name: Download Files
        run: |
          mkdir downloads

          while read url
          do
            yt-dlp \
              --no-warnings \
              --restrict-filenames \
              -P downloads \
              "$url"
          done < links.txt

      - name: Zip Files
        run: |
          zip -r files.zip downloads

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: telegram-files
          path: files.zip
