name: Telegram Downloader (No Bot)

on:
  workflow_dispatch:
    inputs:
      links:
        description: "Telegram links (one per line)"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gallery-dl
        run: pip install gallery-dl

      - name: Save links
        run: |
          echo "${{ github.event.inputs.links }}" > links.txt
          mkdir out

      - name: Download
        run: |
          while read url
          do
            gallery-dl -D out "$url"
          done < links.txt

      - name: Zip output
        run: zip -r result.zip out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-download
          path: result.zip
